### ISSUE TITLE
NullPointerException: Parameter specified as non-null is null

### ISSUE THREAD

**Issue by autoreleasefool** [autoreleasefool/approach#547]
method ca.josephroque.bowlingcompanion.core.model.TeamListItem.<init>, parameter members

```
java.lang.NullPointerException: Parameter specified as non-null is null: method ca.josephroque.bowlingcompanion.core.model.TeamListItem.<init>, parameter members
    at ca.josephroque.bowlingcompanion.core.model.TeamListItem.<init>
    at ca.josephroque.bowlingcompanion.core.model.TeamListItem.<init>
    at ca.josephroque.bowlingcompanion.core.database.dao.TeamDao_Impl$getTeamList$1.call(TeamDao_Impl.kt:238)
    at ca.josephroque.bowlingcompanion.core.database.dao.TeamDao_Impl$getTeamList$1.call(TeamDao_Impl.kt:213)
    at androidx.room.CoroutinesRoom$Companion$createFlow$1$1$1.invokeSuspend(CoroutinesRoom.kt:129)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
    at java.lang.Thread.run(Thread.java:1012)
```

**Comment by autoreleasefool** [comment]
Fixed in fda8b131a
