### ISSUE TITLE
Resources$NotFoundException

### ISSUE THREAD

**Issue by autoreleasefool** [autoreleasefool/approach#548]
Thought this was fixed in #535, may be duplicate of #534

```
android.content.res.Resources$NotFoundException: Resource ID #0x7f080070
    at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:215)
    at android.content.res.Resources.getValue(Resources.java:1316)
    at androidx.compose.ui.res.ResourceIdCache.resolveResourcePath(Resources.android.kt:56)
    at androidx.compose.ui.res.PainterResources_androidKt.painterResource(PainterResources.android.kt:65)
    at ca.josephroque.bowlingcompanion.feature.onboarding.ui.newuser.NewUserOnboardingKt$AppDescription$1.invoke(NewUserOnboarding.kt:78)
    at ca.josephroque.bowlingcompanion.feature.onboarding.ui.newuser.NewUserOnboardingKt$AppDescription$1.invoke(NewUserOnboarding.kt:69)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
    at ca.josephroque.bowlingcompanion.feature.onboarding.ui.components.OnboardingBackgroundKt.ReadableContent(OnboardingBackground.kt:81)
    at ca.josephroque.bowlingcompanion.feature.onboarding.ui.newuser.NewUserOnboardingKt.AppDescription(NewUserOnboarding.kt:69)
    at ca.josephroque.bowlingcompanion.feature.onboarding.ui.newuser.NewUserOnboardingKt.access$AppDescription(NewUserOnboarding.kt:1)
    at ca.josephroque.bowlingcompanion.feature.onboarding.ui.newuser.NewUserOnboardingKt$NewUserOnboarding$2$2.invoke(NewUserOnboarding.kt:54)
    at ca.josephroque.bowlingcompanion.feature.onboarding.ui.newuser.NewUserOnboardingKt$NewUserOnboarding$2$2.invoke(NewUserOnboarding.kt:52)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:118)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
    at androidx.compose.animation.AnimatedVisibilityKt.AnimatedEnterExitImpl(AnimatedVisibility.kt:771)
    at androidx.compose.animation.AnimatedVisibilityKt$AnimatedEnterExitImpl$4.invoke
    at androidx.compose.animation.AnimatedVisibilityKt$AnimatedEnterExitImpl$4.invoke
    at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:192)
    at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2825)
    at androidx.compose.runtime.ComposerImpl.skipToGroupEnd(Composer.kt:3139)
    at androidx.compose.animation.AnimatedVisibilityKt.AnimatedVisibilityImpl(AnimatedVisibility.kt:715)
    at androidx.compose.animation.AnimatedVisibilityKt.AnimatedVisibility(AnimatedVisibility.kt:387)
    at androidx.compose.animation.AnimatedVisibilityKt$AnimatedVisibility$8.invoke
    at androidx.compose.animation.AnimatedVisibilityKt$AnimatedVisibility$8.invoke
    at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:192)
    at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2825)
    at androidx.compose.runtime.ComposerImpl.skipToGroupEnd(Composer.kt:3139)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$5.invoke(AnimatedContent.kt:804)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$5.invoke(AnimatedContent.kt:792)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:118)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
    at androidx.compose.animation.AnimatedVisibilityKt.AnimatedEnterExitImpl(AnimatedVisibility.kt:771)
    at androidx.compose.animation.AnimatedVisibilityKt$AnimatedEnterExitImpl$4.invoke
    at androidx.compose.animation.AnimatedVisibilityKt$AnimatedEnterExitImpl$4.invoke
    at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:192)
    at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2825)
    at androidx.compose.runtime.ComposerImpl.skipToGroupEnd(Composer.kt:3139)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1.invoke(AnimatedContent.kt:805)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1.invoke(AnimatedContent.kt:757)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
    at androidx.compose.animation.AnimatedContentKt.AnimatedContent(AnimatedContent.kt:816)
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$9.invoke
    at androidx.compose.animation.AnimatedContentKt$AnimatedContent$9.invoke
    at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:192)
    at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2825)
    at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:3116)
    at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3607)
    at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3552)
    at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:948)
    at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1206)
    at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:132)
    at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:616)
    at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:585)
    at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
    at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
    at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
    at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
    at android.view.Choreographer.doCallbacks(Choreographer.java:723)
    at android.view.Choreographer.doFrame(Choreographer.java:655)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
    at android.os.Handler.handleCallback(Handler.java:790)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6494)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by autoreleasefool** [comment]
Fixed in 3a6cc3ca1
