### ISSUE TITLE
java.lang.ClassCastException: ca.josephroque.bowlingcompanion.core.model.SeriesID cannot be cast to java.util.Set

### ISSUE THREAD

**Issue by autoreleasefool** [autoreleasefool/approach#549]
```
java.lang.ClassCastException: ca.josephroque.bowlingcompanion.core.model.SeriesID cannot be cast to java.util.Set
    at ca.josephroque.bowlingcompanion.feature.resourcepicker.navigation.ResourcePickerNavigationKt$navigateToAlleyPickerForResult$3.invoke(ResourcePickerNavigation.kt:132)
    at ca.josephroque.bowlingcompanion.core.navigation.NavigationForResultKt.popBackStackWithResult(NavigationForResult.kt:40)
    at ca.josephroque.bowlingcompanion.navigation.graph.OverviewGraphKt$overviewGraph$28.invoke--cuGr9M(OverviewGraph.kt:139)
    at ca.josephroque.bowlingcompanion.navigation.graph.OverviewGraphKt$overviewGraph$28.invoke(OverviewGraph.kt:139)
    at ca.josephroque.bowlingcompanion.feature.seriesform.SeriesFormScreenKt$SeriesFormRoute$1$1$1$1.emit(SeriesFormScreen.kt:43)
    at ca.josephroque.bowlingcompanion.feature.seriesform.SeriesFormScreenKt$SeriesFormRoute$1$1$1$1.emit(SeriesFormScreen.kt:41)
    at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:37)
    at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
    at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
    at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:68)
    at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:375)
    at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
    at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
    at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
    at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
    at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
    at kotlinx.coroutines.BuildersKt.launch
    at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
    at kotlinx.coroutines.BuildersKt.launch$default
    at ca.josephroque.bowlingcompanion.core.common.viewmodel.ApproachViewModel.sendEvent(ApproachViewModel.kt:13)
    at ca.josephroque.bowlingcompanion.feature.seriesform.SeriesFormViewModel.dismiss--cuGr9M(SeriesFormViewModel.kt:390)
    at ca.josephroque.bowlingcompanion.feature.seriesform.SeriesFormViewModel.access$dismiss--cuGr9M(SeriesFormViewModel.kt:39)
    at ca.josephroque.bowlingcompanion.feature.seriesform.SeriesFormViewModel$saveSeries$1.invokeSuspend(SeriesFormViewModel.kt:376)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
    at android.os.Handler.handleCallback(Handler.java:900)
    at android.os.Handler.dispatchMessage(Handler.java:103)
    at android.os.Looper.loop(Looper.java:219)
    at android.app.ActivityThread.main(ActivityThread.java:8393)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

**Comment by autoreleasefool** [comment]
Looks like this was related to 447d44f
