### ISSUE TITLE
ArithmeticException: divide by zero

### ISSUE THREAD

**Issue by autoreleasefool** [autoreleasefool/approach#560]
### Sentry

https://approach-bowling.sentry.io/issues/5891740629/?project=4506432676036608&query=is:unresolved%20issue.priority:%5Bhigh,%20medium%5D&statsPeriod=14d&stream_index=1

### Stacktrace

```
java.lang.ArithmeticException: divide by zero
    at ca.josephroque.bowlingcompanion.feature.gameseditor.utils.GameUtilitiesKt.updateHeader(GameUtilities.kt:215)
    at ca.josephroque.bowlingcompanion.feature.gameseditor.GamesEditorViewModel.setCurrentSelection(GamesEditorViewModel.kt:987)
    at ca.josephroque.bowlingcompanion.feature.gameseditor.GamesEditorViewModel.access$setCurrentSelection(GamesEditorViewModel.kt:108)
    at ca.josephroque.bowlingcompanion.feature.gameseditor.GamesEditorViewModel$loadGame$12$1.emit(GamesEditorViewModel.kt:723)
    at ca.josephroque.bowlingcompanion.feature.gameseditor.GamesEditorViewModel$loadGame$12$1.emit(GamesEditorViewModel.kt:712)
    at ca.josephroque.bowlingcompanion.core.data.repository.OfflineFirstFramesRepository$getFrames-yh3CJiE$$inlined$map$1$2.emit(Emitters.kt:223)
    at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
    at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
    at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:87)
    at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:66)
    at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:37)
    at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
    at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
    at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by autoreleasefool** [comment]
Resolved by: cff954639

Issue was that initial loading of a team game could load the game details + bowlers out of order (all asynchronous) and not having bowlers loaded before the game details caused a crash due to modulo division.

Fix is to skip this calculation/state update until the bowlers have loaded
